//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.02.26 at 09:30:30 PM IST 
//


package editor.model.xsd.jaxb;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for BaseJoin complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="BaseJoin">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="howMany" type="{http://www.w3.org/2001/XMLSchema}int" default="1" />
 *       &lt;attribute name="targetEntityFqn" use="required" type="{http://www.w3.org/2001/XMLSchema}string" />
 *       &lt;attribute name="arrowHead" default="None">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="None"/>
 *             &lt;enumeration value="Empty"/>
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="EmptyDiamond"/>
 *             &lt;enumeration value="SolidDiamond"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lineType" default="Solid">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Solid"/>
 *             &lt;enumeration value="Dashed"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="joinName" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "BaseJoin")
@XmlSeeAlso({
    ColumnTitleJoin.class,
    TitleColumnJoin.class,
    GroupGroupJoin.class,
    ColumnColumnJoin.class
})
public class BaseJoin {

    @XmlAttribute(name = "howMany")
    protected Integer howMany;
    @XmlAttribute(name = "targetEntityFqn", required = true)
    protected String targetEntityFqn;
    @XmlAttribute(name = "arrowHead")
    protected String arrowHead;
    @XmlAttribute(name = "lineType")
    protected String lineType;
    @XmlAttribute(name = "joinName")
    protected String joinName;

    /**
     * Gets the value of the howMany property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public int getHowMany() {
        if (howMany == null) {
            return  1;
        } else {
            return howMany;
        }
    }

    /**
     * Sets the value of the howMany property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setHowMany(Integer value) {
        this.howMany = value;
    }

    /**
     * Gets the value of the targetEntityFqn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTargetEntityFqn() {
        return targetEntityFqn;
    }

    /**
     * Sets the value of the targetEntityFqn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTargetEntityFqn(String value) {
        this.targetEntityFqn = value;
    }

    /**
     * Gets the value of the arrowHead property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getArrowHead() {
        if (arrowHead == null) {
            return "None";
        } else {
            return arrowHead;
        }
    }

    /**
     * Sets the value of the arrowHead property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setArrowHead(String value) {
        this.arrowHead = value;
    }

    /**
     * Gets the value of the lineType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineType() {
        if (lineType == null) {
            return "Solid";
        } else {
            return lineType;
        }
    }

    /**
     * Sets the value of the lineType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineType(String value) {
        this.lineType = value;
    }

    /**
     * Gets the value of the joinName property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getJoinName() {
        return joinName;
    }

    /**
     * Sets the value of the joinName property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setJoinName(String value) {
        this.joinName = value;
    }

}
